[Inference] Add validated models for Gaudi
intel/llm-on-ray pull request #225
Opened 2024-05-16 15:31 UTC by Deegue

Model list:
Falcon-7b single card
Falcon-40b multiple cards
Llama3-7b single card
Llama3-70b multiple cards
Mistral-7b single card
Gemma-2b single card
CodeLlama single card
GPT2 single card
GPT-J single card
MPT-7b single card

2024-05-20 03:24 UTC, carsonwang reviewed
@Deegue, although the result showed pass but they actually failed. Please check the run result. So can you please check the response of the model for the tests.

2024-05-20 03:24 UTC, carsonwang commented on llm_on_ray/inference/models/hpu/MindChat-Qwen2-4B-hpu.yaml
> +  model_id_or_path: X-D-Lab/MindChat-Qwen2-4B
Not this one. Please use Qwen/Qwen1.5-7B

2024-05-20 03:24 UTC, carsonwang commented on llm_on_ray/inference/models/hpu/CodeLlama-7b-hf-hpu.yaml
> +  chat_processor: ChatModelGptJ
This config file is not correct. Please refer to the existing yaml file for CPU.

2024-06-12 02:55 UTC, Deegue commented
All CI passed. Gentle ping @carsonwang for review, thanks!

2024-06-12 05:30 UTC, carsonwang commented
@kira-lin is helping to review this. For qwen, can you please update to use Qwen/Qwen2-7B-Instruct?

2024-06-12 09:34 UTC, Deegue commented
> @kira-lin is helping to review this. For qwen, can you please update to use Qwen/Qwen2-7B-Instruct?

Added `Qwen1.5-7B-Chat` and `Qwen2-7B-Instruct`.

2024-06-13 02:30 UTC, kira-lin requested changes
Qwen 110 not tested.
Many models output weird things, including mpt mistral gpt2 gemma falcon 7b/40b bloom.
Compare them with CPU/GPU to see if it's normal behavior. For example, codellama is outputting some markup language, but I think it's tuned that way. Also pay attention to temperature, which might lead to random result, and it might be different for different models

2024-06-13 02:31 UTC, kira-lin commented
For falcon and qwen, @KepingYan can look into this.

2024-06-13 05:13 UTC, carsonwang commented on llm_on_ray/inference/models/hpu/Qwen1.5-110B-hpu.yaml
> +port: 8000
Please remove this file.

2024-06-13 05:13 UTC, carsonwang commented on llm_on_ray/inference/models/hpu/Qwen1.5-7B-Chat-hpu.yaml
> +port: 8000
Please also remove this file.

2024-06-13 05:14 UTC, carsonwang commented on llm_on_ray/inference/models/hpu/Mixtral-7B-hpu.yaml
> +port: 8000
Also remove this one. Add it back after running successfully.

2024-06-17 03:22 UTC, KepingYan requested changes
https://github.com/intel/llm-on-ray/blob/cdce225cb2285baf9c151fecc7b6af853412e030/llm_on_ray/inference/predictors/hpu_predictor.py#L340

Let's modify this line according to:
https://github.com/huggingface/optimum-habana/blob/595cc3e4ec219b1ce469b323cf94e994c5c5d8f3/examples/text-generation/utils.py#L311-L312

2024-06-18 05:48 UTC, Deegue commented
> https://github.com/intel/llm-on-ray/blob/cdce225cb2285baf9c151fecc7b6af853412e030/llm_on_ray/inference/predictors/hpu_predictor.py#L340
> 
> Let's modify this line according to: https://github.com/huggingface/optimum-habana/blob/595cc3e4ec219b1ce469b323cf94e994c5c5d8f3/examples/text-generation/utils.py#L311-L312

Updated, thanks for comment. Btw, will it still be any place to be changed since I found some other places specially handled through `model_type == llama`?

2024-07-18 02:31 UTC, carsonwang approved these changes

2024-07-18 02:36 UTC, closed without merging