[UI] remove relative import and fix log level
intel/llm-on-ray pull request #79
Opened 2024-01-22 08:17 UTC by KepingYan

2024-01-29 09:14 UTC, xwu99 commented on docs/web_ui.md
> +After activating the environment installed in previous step, please run the following script to install environment for ui.
```suggestion
After activating the environment installed in the previous step, please run the following script to install environment for ui.
```

2024-01-29 09:16 UTC, xwu99 commented on docs/web_ui.md
> +After activating the environment installed in previous step, please run the following script to install environment for ui.
```suggestion
After activating the environment installed in previous step, please run the following script to install environment for Web UI.
```

2024-01-29 09:22 UTC, xwu99 commented on docs/web_ui.md
Need to rephrase: 
# Get urls from the log
# Running on local URL:  http://0.0.0.0:8080
# Running on public URL: https://180cd5f7c31a1cfd3c.gradio.live

Get URL from the command line output (E.g. `http://0.0.0.0:8080` for local network and `https://180cd5f7c31a1cfd3c.gradio.live` for public network) and use the browser to open it.

2024-01-29 09:25 UTC, xwu99 commented on ui/start_ui.py
> +from predictor_deployment import PredictorDeployment
insert a blank line

2024-01-29 09:28 UTC, xwu99 requested changes

2024-01-29 09:28 UTC, xwu99 commented on ui/start_ui.py
> +from predictor_deployment import PredictorDeployment
insert a blank line

2024-01-29 09:28 UTC, xwu99 commented on ui/start_ui.py
> +                        value=base_models_list[4],
add comment for using constant, what is the value you are specifying here. Same below

2024-02-05 02:13 UTC, KepingYan commented
Close this first as I‘ll address https://github.com/intel/llm-on-ray/issues/72 and https://github.com/intel/llm-on-ray/pull/90 in two separate PRs. Thanks @xwu99.

2024-02-05 02:13 UTC, closed without merging